### ISSUE TITLE
Elektromechanické řešení odpojování vírníku

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TF-SIMPLEPLATFORM#1]
Návrh od @taury55 
![246345183_863760754339185_2732345601950476159_n](https://user-images.githubusercontent.com/1194177/137742524-ad8b64c4-5cc5-4568-b218-ca0b777881b4.jpg)

Možnosti odpojovacích zámků: 
- https://www.gme.cz/elektromagneticke-zamky?
- https://dratek.cz/8806-tazne-elektromagnety/#sc=342

**Comment by kaklik** [comment]
Vzhledem k tomu, že se ukazuje jako komplikované vyřešit prostup pro zámek skrz pláštěnku na trupu. Tak jsme dnes s @roman-dvorak  vymysleli řešení, kdy by vírník byl uchycen pouze za vnější části mimo pláštěnku. Konkrétně za ocasní trubku a podvozkové nohy. 

![IMG_20211018_213610](https://user-images.githubusercontent.com/1194177/137795492-b552dd61-dcfd-4b73-8bf3-b3bcf39f4a32.jpg)

Čtvrtý bod uchycení by bylo místo ze kterého se bude odpojovat zámek.  Výhodou tohoto řešení je fakt, že pak stačí pouze jeden akční člen k uchycení vírníku.

**Comment by taury55** [comment]
První náhled na novou platformu vypadá takto. (Zatím jsou jen pasivní prvky)

![2021-11-02-133258_1366x768_scrot](https://user-images.githubusercontent.com/33667517/139847311-9df327ed-b433-4f63-b902-3cfd975b7cc1.png)

Zjistil jsem že 400mm, které používá TF-MOTORSCALE je celkem těsné/stísněné pro platformu TF-G2. trochu uvažuji o vynechání zadní podpory a pouze nechat zámek.

**Comment by roman-dvorak** [comment]
To vypadá zajímavě. Ty Učka, co drží podvozkové nohy (i ocasní tyč) jsem si představoval o dost mělčí. 

Nešlo by tu zadní podpěru celotištěnou? 

Myslím, že váze nevadí, že profil bude trochu protažený dopředu.

**Comment by taury55** [comment]
> To vypadá zajímavě. Ty Učka, co drží podvozkové nohy (i ocasní tyč) jsem si představoval o dost mělčí.
> 
> Nešlo by tu zadní podpěru celotištěnou?
> 
> Myslím, že váze nevadí, že profil bude trochu protažený dopředu.

Mělčí samozrejmě není problém.

Myslíš jako nepoužít ten ALU profil? Jestli ano, tak jsem ho použil, protože máme dost takhle malých zbytků a mám díky tomu nějakou pevnost navíc bez kreslení.

Nevadí mít profil více dopředu, ale použil jsem délku, která je aktuálně na TF-MOTORSCALE, takže bychom museli udělat nový.

**Comment by kaklik** [comment]
> 
> Zjistil jsem že 400mm, které používá TF-MOTORSCALE je celkem těsné/stísněné pro platformu TF-G2. trochu uvažuji o vynechání zadní podpory a pouze nechat zámek.

Ten návrh vypadá dost designově. :D 
Myslím si, že není možné vynechat zadní podporu a použít pouze zámek, protože záklon vírníku drží podpora v kombinaci se zámkem. 
Pokud je nutné použít delší profil, tak bych spíše navrhoval na motorovou váhu připevnit další profil na ten, který tam aktuálně je.

**Comment by roman-dvorak** [comment]
> Myslíš jako nepoužít ten ALU profil? Jestli ano, tak jsem ho použil, protože máme dost takhle malých zbytků a mám díky tomu nějakou pevnost navíc bez kreslení.

Ano, úplně zbytečně to pak zesložiťuje další výrobu a dalši skládání. Je tam zbytečný spoj navíc.

**Comment by taury55** [comment]
Takto by zhruba vypadal zámek se solenoidem. Je nutné aby solenoid měl délku posunu alespoň 15mm, aby se čelisti rozevřeli, co nejvíce. Na obrázku je rozevření čelistí přibližně, pokud by byl posun přesně na 15mm. Jako referenci jsem používal tento solenoid, který má posun kolem 15-20mm. https://www.tme.eu/en/details/282367-024/solenoids/saia-burgess/ 
![2021-11-02-150031_1366x768_scrot](https://user-images.githubusercontent.com/33667517/139861974-f900cd23-6c7a-4a33-8b49-381fcee730c4.png)

**Comment by roman-dvorak** [comment]
Délka posuvu X rozevření kleští lze ovlivnit tím, jak daleo od osy rozevírání kleští bude táhlo ukotveno. To však bude ovlivňovat výslednou sílu rozevření. Je proto potřeba najít nějaké optimum, protože i magnet s délkou výsuvu ztrácí sílu.

**Comment by taury55** [comment]
Jo, to si uvědomuju. Ale zjistil jsem, že solenoidy je problém sehnat s delším posuvem. Ale s větší sílou není.

Dodělal jsem to jako gif, který počítá to nahnutí v závislosti na posunu solenoidu. Zanedbávám to, že tahám lineárně za ten úchytný bod, ale to už by neměl být téměř žádný rozdíl.

**Comment by taury55** [comment]
Takto bych si nyní představoval zámek. Zvolil jsem nakonec servo (D485HW) z těchto důvodů:

- Solenoidy se pro naše požadované síly dělají velmi málo a dokonce je potřeba použít větší výkon než, který dokáží trvale uchladit.
- Solenoidy, které by potencionálně mohli být na našem zámku jsou beze pružiny. Proto je nutné použit pro vracení/držení v zamknuté poloze nezávislá pružina, což komplikuje konstrukci a sestavení zámku.
- Solenoidy ztrácí sílu exponenciálně, takže mají velmi omezený rozsah pohybu, což zveličuje dva ostatní faktory.

![2021-11-21-180546_1366x768_scrot](https://user-images.githubusercontent.com/33667517/142771874-ea6245d9-66f7-43f8-9dcc-d4639f7fc66f.png)
Graf síly, kterou může působit na různé vzdálenosti jeden z nejsilnějších solenoidů, které jsem našel a chtěl použít.

Takto by zámek fungoval.
![servo_lock](https://user-images.githubusercontent.com/33667517/142771565-d5dc7a3d-38bf-41b2-84f9-ee86a8ee4e43.gif)

**Comment by kaklik** [comment]
Ok, to vypadá dobře. :)  Ten mechanismus by to asi chtělo zkusit vyrobit v nějaké základní verzi a vyzkoušet na trubce s generátorem signálu pro serva. 

Pak ale vznikla ještě otázka jakým způsobem budeme ovládat to servo? Přidáme k tomu nějaký arduino?

**Comment by roman-dvorak** [comment]
Jo, bylo by fajn k tomu přidat arduino s tlačítkem, LEDkou a USB sériovkou. Přes kterou by to dostávalo příkaz z pythonu.

**Comment by taury55** [comment]
Zatím pouze testování zda a co funguje, ale pomalinku bychom mohli mít první prototyp.


Tady jsem upravil trochu geometrii a přidal jsem číslo pro animaci, které zobrazuje aktuální rozevření čelistí.
![ezgif com-gif-maker(1)](https://user-images.githubusercontent.com/33667517/143919449-02eabad9-a819-48d8-a720-18a6afa16170.gif)

**Comment by slimonslimon** [comment]
zvědavý dotaz, vůbec nesouvisející s tématem: Jak děláš ty animace?

**Comment by taury55** [comment]
Je to strašně jednoduché. Stačí přidat proměnou `$t` a ta se mění z 0 na 1 v závislosti na čase animace.
Poté se v OpenSCADu v menu "view" zaškrtne políčko "animate", které zapína menu pro volbu FPS a počtu snímků.
Poslední iterace jsem udělal pomocí cosínu, aby docílil toho jemného přechodu.
[https://www.instructables.com/Animating-with-OpenSCAD/](Instructables - Návod na animace v OpenSCADu)

**Comment by taury55** [comment]
Mechanismus zámku poprvé otestován v realném světě.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/33667517/143953759-75ee2947-c70f-4f3d-98c4-bb7b0efed176.gif)

Testování síly serva na držení tyčky:
https://user-images.githubusercontent.com/33667517/143953920-2548221a-6896-4648-88ac-2952e82de2f8.mp4

Projevil se problém s tolerancema, které jsem upravoval. První výtisk měl až moc velký odpor. A tak jsem zvedl tolerance děr a tím vznikl nepříjemný "backslash" (nevím jak je to v češtině...), který je potřeba do další verze opravit. Jinak vypadá zámek funkčně a připraven na první testování. Také je možno vidět, že servo utíká. Není připevněno na pevno, protože nemám doma M2.5 šrouby a hlavně matice a také tím servo nemohu zníčit.
https://user-images.githubusercontent.com/33667517/143954089-8f5fc323-e213-4be6-abc5-6170f31f755c.mp4

**Comment by roman-dvorak** [comment]
Možná by bylo vhodné, aby se ty kleštiny v zavřeném stavu neopíraly o sebe. Aby mezi nimi byla malá mezera a domáčklo se to k trubce ocasu. Možná by se tam mohla vlepit nějaká tenká guma (např. z duše od kola). 

![obrazek](https://user-images.githubusercontent.com/5196729/144875349-9034ec9f-c742-489f-820b-1c78af5eaac0.png)
Aby v (především) vyznačených místech byla nějaká mezera. V zavřeném stavu.

**Comment by taury55** [comment]
Zatím jsem tiskl dvě varianty čelistí. Obě neměli problém s držením trubky, ale trubka měla volnost ve svojí ose, takže mohla rotovat v ose letu. Tak nevím jestli je to žádané nebo ne. Takže to nevidím jako nutné. Spíše, jestli chceme držet ve všech osách nebo v zámku bude tato osa volná a bude držet pomocí těch podpor.

Tomu pohybu, co aktuálně stejně v zámku moc zabránit, protože, když se tam dá např guma, tak bude všechna síla v té ose pusobit pouze na tu gumu a snažit se jí vyrvat.

**Comment by taury55** [comment]
Myslím, že mechanická část je hotová.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/33667517/145199846-9bce2bac-4c48-44a5-8a02-1203b1b1ec31.gif)

**Comment by slimonslimon** [comment]
Vypadá to cool.

Jak dobře to jde ta trubka vypáčit?

(teď tě čeká ta softwarová... upřímnou soustrast)

**Comment by taury55** [comment]
Pokud ji člověk nechce vytáhnout, tak se člověk musí dost snažit. Kombinace 50 N a té geometrie je úplně dostatečná. A v realitě to pocitově celkem odpovídá, že ta síla taková.

@kaklik @roman-dvorak Co se týče ovládání, tak bych tam dal ESP32, které by se automaticky připojovalo na wifi auta. Reagovalo na naarmování a pokyn pro vypuštění. Co si o tom myslíte?

**Comment by roman-dvorak** [comment]
Super, tohle vypadá hezky a dost použitelně! 

Co se týče ovládání, popsal jsem to do vlastního issue: https://github.com/ThunderFly-aerospace/Simple-platform/issues/3

**Comment by roman-dvorak** [comment]
Ještě tedy je potřeba domodelovat ty zbylé dvě podpěry.

**Comment by kaklik** [comment]
Tohle považuji za hotové. Potenciálním vylepšením je vytvoření asymetrických podpěr pod přední podvozkové nohy, aby vírník z podpěr nemohl vypadnout směrem dozadu.  Nemyslím si ale že je to v případě použití vírníku s nepopraskanou podložkou nějaký problém.
