### ISSUE TITLE
Weatherproofing

### ISSUE THREAD

**Issue by kaklik** [ThunderFly-aerospace/TF-SIMPLEPLATFORM#7]
Myslím že aby s platformou bylo možné jet měřit i do bouřky, tak je nutné, aby byla odolná proti dešti.   V aktuální situaci to lze zřejmě nejsnáze zajistit ušitím voděodolné pláštěnky přes celou platformu.

FYI @kakl.

**Comment by slimonslimon** [comment]
na platformně je nějaké místo kam může zatéct a byl by to problém?

**Comment by taury55** [comment]
> na platformně je nějaké místo kam může zatéct a byl by to problém?

Bude to nový box na elektroniku a pneumatiku, proto potřebuje krytování.

**Comment by kaklik** [comment]
Myslím že poslední varianta platformy je proti vodě už odolná dostatečně, akorát to asi není produkční řešení. Zatím ale lze tento problém považovat za uzavřený.
